version: "3.8"

services:
  site:
    image: jekyll/jekyll:3.8
    command: ["jekyll", "serve", "-H", "0.0.0.0", "-P", "4000", "--livereload"]
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ".:/srv/jekyll"
      - "./vendor/bundle:/usr/local/bundle"
