name: Build and Deploy

on:
  push:
    branches:
      - master   # Only on master now

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install and Build 🔧
        run: |
          pnpm install
          pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
